[[redirects]]
from = "https://b-alexandre-portfolio.netlify.app/*"
to = "https://portfolio.bonefons.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://bonefons.com/*"
to = "https://portfolio.bonefons.com/:splat"
status = 301
force = true
